apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-dep
  name: demo-dep
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: demo-dep
  type: NodePort
status:
  loadBalancer: {}